In [12]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/xontoloyo/data-penjualan-zara/zara.csv
/kaggle/input/datasets/rakeshgope/zara-sales-csv/zara.xlsx
/kaggle/input/datasets/rakeshgope/zara-salessss/zara sales.csv

In [13]:
#1. Import Libraries
import pandas as pd
import numpy as np

In [14]:
#2. Load Dataset
df= pd.read_csv('/kaggle/input/datasets/rakeshgope/zara-salessss/zara sales.csv')

In [15]:
#3. Basic Exploration
df.head()

,Product ID,Product Position,Promotion,Product Category,Seasonal,Sales Volume,brand,url,sku,name,description,currency,scraped_at,terms,section
0,185102,Aisle,No,Clothing,No,2823,Zara,https://www.zara.com/us/en/basic-puffer-jacket...,272145190-250-2,BASIC PUFFER JACKET,Puffer jacket made of tear-resistant ripstop f...,USD,2024-02-19T08:50:05.654618,jackets,MAN
1,188771,Aisle,No,Clothing,No,654,Zara,https://www.zara.com/us/en/tuxedo-jacket-p0889...,324052738-800-46,TUXEDO JACKET,Straight fit blazer. Pointed lapel collar and ...,USD,2024-02-19T08:50:06.590930,jackets,MAN
2,180176,End-cap,Yes,Clothing,Yes,2220,Zara,https://www.zara.com/us/en/slim-fit-suit-jacke...,335342680-800-44,SLIM FIT SUIT JACKET,Slim fit jacket. Notched lapel collar. Long sl...,USD,2024-02-19T08:50:07.301419,jackets,MAN
3,112917,Aisle,Yes,Clothing,Yes,1568,Zara,https://www.zara.com/us/en/stretch-suit-jacket...,328303236-420-44,STRETCH SUIT JACKET,Slim fit jacket made of viscose blend fabric. ...,USD,2024-02-19T08:50:07.882922,jackets,MAN
4,192936,End-cap,No,Clothing,Yes,2942,Zara,https://www.zara.com/us/en/double-faced-jacket...,312368260-800-2,DOUBLE FACED JACKET,Jacket made of faux leather faux shearling wit...,USD,2024-02-19T08:50:08.453847,jackets,MAN

In [16]:
df.shape

(252, 15)

In [17]:
df.columns

Index(['Product ID', 'Product Position', 'Promotion', 'Product Category',
       'Seasonal', 'Sales Volume', 'brand', 'url', 'sku', 'name',
       'description', 'currency', 'scraped_at', 'terms', 'section'],
      dtype='object')

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 252 entries, 0 to 251
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Product ID        252 non-null    int64
 1   Product Position  252 non-null    object
 2   Promotion         252 non-null    object
 3   Product Category  252 non-null    object
 4   Seasonal          252 non-null    object
 5   Sales Volume      252 non-null    int64
 6   brand             252 non-null    object
 7   url               252 non-null    object
 8   sku               252 non-null    object
 9   name              251 non-null    object
 10  description       250 non-null    object
 11  currency          252 non-null    object
 12  scraped_at        252 non-null    object
 13  terms             252 non-null    object
 14  section           252 non-null    object
dtypes: int64(2), object(13)
memory usage: 29.7+ KB

In [19]:
df.describe()

          Product ID  Sales Volume
count     252.000000    252.000000
mean   153370.503968   1823.702381
std     26160.444549    697.703748
min    110075.000000    529.000000
25%    131053.750000   1243.000000
50%    151681.500000   1839.500000
75%    175669.750000   2398.750000
max    199631.000000   2989.000000

In [20]:
#4. Check Missing Values
df.isnull().sum()

Product ID          0
Product Position    0
Promotion           0
Product Category    0
Seasonal            0
Sales Volume        0
brand               0
url                 0
sku                 0
name                1
description         2
currency            0
scraped_at          0
terms               0
section             0
dtype: int64

In [21]:
(df.isnull().sum()/len(df))*100

Product ID          0.000000
Product Position    0.000000
Promotion           0.000000
Product Category    0.000000
Seasonal            0.000000
Sales Volume        0.000000
brand               0.000000
url                 0.000000
sku                 0.000000
name                0.396825
description         0.793651
currency            0.000000
scraped_at          0.000000
terms               0.000000
section             0.000000
dtype: float64

In [22]:
df[df['name'].isnull()]

,Product ID,Product Position,Promotion,Product Category,Seasonal,Sales Volume,brand,url,sku,name,description,currency,scraped_at,terms,section
72,173576,End-cap,Yes,Clothing,No,1838,Zara,https://www.zara.com/us/en/-p04310461.html,336378923-700-2,NaN,NaN,USD,2024-02-19T08:50:54.476057,jackets,MAN

In [23]:
df[df['description'].isnull()]

,Product ID,Product Position,Promotion,Product Category,Seasonal,Sales Volume,brand,url,sku,name,description,currency,scraped_at,terms,section
60,151925,End-cap,Yes,Clothing,Yes,2179,Zara,https://www.zara.com/us/en/vintage-effect-leat...,320774184-800-97,VINTAGE EFFECT LEATHER BOMBER JACKET,NaN,USD,2024-02-19T08:50:43.543555,jackets,MAN
72,173576,End-cap,Yes,Clothing,No,1838,Zara,https://www.zara.com/us/en/-p04310461.html,336378923-700-2,NaN,NaN,USD,2024-02-19T08:50:54.476057,jackets,MAN

In [24]:
df = df.dropna(subset=['name', 'description'])

In [25]:
df.isnull().sum()

Product ID          0
Product Position    0
Promotion           0
Product Category    0
Seasonal            0
Sales Volume        0
brand               0
url                 0
sku                 0
name                0
description         0
currency            0
scraped_at          0
terms               0
section             0
dtype: int64

In [26]:
#5. Check Duplicate Records
df.duplicated().sum()

np.int64(0)

In [27]:
#6. Standardize Column Names
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

In [28]:
df.columns

Index(['product_id', 'product_position', 'promotion', 'product_category',
       'seasonal', 'sales_volume', 'brand', 'url', 'sku', 'name',
       'description', 'currency', 'scraped_at', 'terms', 'section'],
      dtype='object')

In [29]:
#7. Convert Data Types
df.dtypes

product_id           int64
product_position    object
promotion           object
product_category    object
seasonal            object
sales_volume         int64
brand               object
url                 object
sku                 object
name                object
description         object
currency            object
scraped_at          object
terms               object
section             object
dtype: object

In [30]:
df['scraped_at'] = pd.to_datetime(df['scraped_at'])

In [31]:
df['sales_volume'] = pd.to_numeric(df['sales_volume'], errors='coerce')

In [32]:
df.dtypes

product_id                   int64
product_position            object
promotion                   object
product_category            object
seasonal                    object
sales_volume                 int64
brand                       object
url                         object
sku                         object
name                        object
description                 object
currency                    object
scraped_at          datetime64[ns]
terms                       object
section                     object
dtype: object

In [33]:
#8. Check Unique Values
df['promotion'].unique()

array(['No', 'Yes'], dtype=object)

In [34]:
df['seasonal'].unique()

array(['No', 'Yes'], dtype=object)

In [35]:
df['product_position'].unique()

array(['Aisle', 'End-cap', 'Front of Store'], dtype=object)

In [36]:
df['terms'].unique()

array(['jackets', 'shoes', 'sweaters', 'jeans', 't-shirts'], dtype=object)

In [37]:
#9. Handle Missing Values
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [product_id, product_position, promotion, product_category, seasonal, sales_volume, brand, url, sku, name, description, currency, scraped_at, terms, section]
Index: []

In [38]:
#10. Check Outliers
df['sales_volume'].describe()

count     250.000000
mean     1822.224000
std       700.136055
min       529.000000
25%      1239.000000
50%      1836.500000
75%      2402.250000
max      2989.000000
Name: sales_volume, dtype: float64

In [39]:
Q1 = df['sales_volume'].quantile(0.25)
Q3 = df['sales_volume'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5*IQR
upper = Q3 + 1.5*IQR

outliers = df[(df['sales_volume'] < lower) | (df['sales_volume'] > upper)]

outliers

Empty DataFrame
Columns: [product_id, product_position, promotion, product_category, seasonal, sales_volume, brand, url, sku, name, description, currency, scraped_at, terms, section]
Index: []

In [40]:
#11. Create New Features
df['promotion_flag'] = df['promotion'].map({
    'Yes':1,
    'No':0
})

In [41]:
df['seasonal_flag'] = df['seasonal'].map({
    'Yes':1,
    'No':0
})

In [42]:
#12. Create Sales Categories
df['sales_category'] = pd.cut(
    df['sales_volume'],
    bins=[0,1000,2000,3000,5000],
    labels=['Low','Medium','High','Very High']
)

In [43]:
#13. Check Final Dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 250 entries, 0 to 251
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   product_id        250 non-null    int64
 1   product_position  250 non-null    object
 2   promotion         250 non-null    object
 3   product_category  250 non-null    object
 4   seasonal          250 non-null    object
 5   sales_volume      250 non-null    int64
 6   brand             250 non-null    object
 7   url               250 non-null    object
 8   sku               250 non-null    object
 9   name              250 non-null    object
 10  description       250 non-null    object
 11  currency          250 non-null    object
 12  scraped_at        250 non-null    datetime64[ns]
 13  terms             250 non-null    object
 14  section           250 non-null    object
 15  promotion_flag    250 non-null    int64
 16  seasonal_flag     250 non-null    int64
 17  sales_category    250 non-null    category
dtypes: category(1), datetime64[ns](1), int64(4), object(12)
memory usage: 35.6+ KB

In [44]:
df.head()

,product_id,product_position,promotion,product_category,seasonal,sales_volume,brand,url,sku,name,description,currency,scraped_at,terms,section,promotion_flag,seasonal_flag,sales_category
0,185102,Aisle,No,Clothing,No,2823,Zara,https://www.zara.com/us/en/basic-puffer-jacket...,272145190-250-2,BASIC PUFFER JACKET,Puffer jacket made of tear-resistant ripstop f...,USD,2024-02-19 08:50:05.654618,jackets,MAN,0,0,High
1,188771,Aisle,No,Clothing,No,654,Zara,https://www.zara.com/us/en/tuxedo-jacket-p0889...,324052738-800-46,TUXEDO JACKET,Straight fit blazer. Pointed lapel collar and ...,USD,2024-02-19 08:50:06.590930,jackets,MAN,0,0,Low
2,180176,End-cap,Yes,Clothing,Yes,2220,Zara,https://www.zara.com/us/en/slim-fit-suit-jacke...,335342680-800-44,SLIM FIT SUIT JACKET,Slim fit jacket. Notched lapel collar. Long sl...,USD,2024-02-19 08:50:07.301419,jackets,MAN,1,1,High
3,112917,Aisle,Yes,Clothing,Yes,1568,Zara,https://www.zara.com/us/en/stretch-suit-jacket...,328303236-420-44,STRETCH SUIT JACKET,Slim fit jacket made of viscose blend fabric. ...,USD,2024-02-19 08:50:07.882922,jackets,MAN,1,1,Medium
4,192936,End-cap,No,Clothing,Yes,2942,Zara,https://www.zara.com/us/en/double-faced-jacket...,312368260-800-2,DOUBLE FACED JACKET,Jacket made of faux leather faux shearling wit...,USD,2024-02-19 08:50:08.453847,jackets,MAN,0,1,High

In [45]:
df.describe(include='all')

,product_id,product_position,promotion,product_category,seasonal,sales_volume,brand,url,sku,name,description,currency,scraped_at,terms,section,promotion_flag,seasonal_flag,sales_category
count,250.000000,250,250,250,250,250.000000,250,250,250,250,250,250,250,250,250,250.000000,250.000000,250
unique,NaN,3,2,1,2,NaN,1,226,226,193,221,1,NaN,5,2,NaN,NaN,3
top,NaN,Aisle,No,Clothing,Yes,NaN,Zara,https://www.zara.com/us/en/hooded-technical-ja...,316727555-700-2,PLAID OVERSHIRT,Varsity jacket with elastic collar and long sl...,USD,NaN,jackets,MAN,NaN,NaN,High
freq,NaN,97,132,250,127,NaN,250,2,2,6,4,250,NaN,138,216,NaN,NaN,114
mean,153295.464000,NaN,NaN,NaN,NaN,1822.224000,NaN,NaN,NaN,NaN,NaN,NaN,2024-02-19 08:57:14.485537792,NaN,NaN,0.472000,0.508000,NaN
min,110075.000000,NaN,NaN,NaN,NaN,529.000000,NaN,NaN,NaN,NaN,NaN,NaN,2024-02-19 08:50:05.654618,NaN,NaN,0.000000,0.000000,NaN
25%,130565.250000,NaN,NaN,NaN,NaN,1239.000000,NaN,NaN,NaN,NaN,NaN,NaN,2024-02-19 08:50:45.921983232,NaN,NaN,0.000000,0.000000,NaN
50%,151417.000000,NaN,NaN,NaN,NaN,1836.500000,NaN,NaN,NaN,NaN,NaN,NaN,2024-02-19 08:51:40.378363392,NaN,NaN,0.000000,1.000000,NaN
75%,175841.250000,NaN,NaN,NaN,NaN,2402.250000,NaN,NaN,NaN,NaN,NaN,NaN,2024-02-19 09:00:48.096932352,NaN,NaN,1.000000,1.000000,NaN
max,199631.000000,NaN,NaN,NaN,NaN,2989.000000,NaN,NaN,NaN,NaN,NaN,NaN,2024-02-19 09:10:52.485772,NaN,NaN,1.000000,1.000000,NaN
std,26233.797778,NaN,NaN,NaN,NaN,700.136055,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.500217,0.500939,NaN

In [46]:
#14. Export Cleaned Dataset
df.to_csv('zara_sales_cleaned.csv', index=False)

Exploratory Data Analysis (EDA)****

In [47]:
#1. Summary Statistics
df.describe()

,product_id,sales_volume,scraped_at,promotion_flag,seasonal_flag
count,250.000000,250.000000,250,250.000000,250.000000
mean,153295.464000,1822.224000,2024-02-19 08:57:14.485537792,0.472000,0.508000
min,110075.000000,529.000000,2024-02-19 08:50:05.654618,0.000000,0.000000
25%,130565.250000,1239.000000,2024-02-19 08:50:45.921983232,0.000000,0.000000
50%,151417.000000,1836.500000,2024-02-19 08:51:40.378363392,0.000000,1.000000
75%,175841.250000,2402.250000,2024-02-19 09:00:48.096932352,1.000000,1.000000
max,199631.000000,2989.000000,2024-02-19 09:10:52.485772,1.000000,1.000000
std,26233.797778,700.136055,NaN,0.500217,0.500939

In [48]:
#2. Sales Volume Distribution
df['sales_volume'].describe()

count     250.000000
mean     1822.224000
std       700.136055
min       529.000000
25%      1239.000000
50%      1836.500000
75%      2402.250000
max      2989.000000
Name: sales_volume, dtype: float64

In [49]:
#3. Top Selling Products
df[['name','sales_volume']].sort_values(
    by='sales_volume',
    ascending=False
).head(10)

                            name  sales_volume
125      PLAID TIE DYE OVERSHIRT          2989
237    SUIT JACKET IN 100% LINEN          2985
246            RIB COLLAR JACKET          2973
5      CONTRASTING COLLAR JACKET          2968
4            DOUBLE FACED JACKET          2942
34    FAUX LEATHER BOMBER JACKET          2931
66                 COTTON JACKET          2929
204    RIPPED STRAIGHT FIT JEANS          2914
181  GATHERED WAIST KNIT SWEATER          2901
206            PURL KNIT SWEATER          2887

#4. Promotion Impact
Questions:

Do promoted products sell more?
What is the average sales volume for promoted vs non-promoted products?

In [50]:

df.groupby('promotion')['sales_volume'].agg(
    ['count','mean','sum']
)

           count         mean     sum
promotion
No           132  1820.545455  240312
Yes          118  1824.101695  215244

#5. Product Position Performance
Questions:

Does Front Store perform better than Aisle?
Which position generates the most sales?

In [51]:

df.groupby('product_position')['sales_volume'].agg(
    ['count','mean','sum']
).sort_values(by='sum', ascending=False)

                  count         mean     sum
product_position
Aisle                97  1828.824742  177396
End-cap              84  1772.773810  148913
Front of Store       69  1873.144928  129247

#6. Seasonal vs Non-Seasonal
Questions:

Do seasonal products sell better?
What percentage of sales comes from seasonal products?

In [52]:

df.groupby('seasonal')['sales_volume'].agg(
    ['count','mean','sum']
)

          count         mean     sum
seasonal
No          123  1825.642276  224554
Yes         127  1818.913386  231002

#7. Section Analysis

In [53]:

df.groupby('section')['sales_volume'].agg(
    ['count','mean','sum']
)

         count         mean     sum
section
MAN        216  1815.657407  392182
WOMAN       34  1863.941176   63374

#8. Product Categories
Questions:

Which product categories generate the highest sales?
Jackets vs Shirts vs Pants, etc

In [54]:

df.groupby('terms')['sales_volume'].sum().sort_values(
    ascending=False)

terms
jackets     255451
sweaters     75242
shoes        57906
t-shirts     53637
jeans        13320
Name: sales_volume, dtype: int64

In [55]:
#9. Export for SQL
df.to_csv('zara_sales_cleaned.csv', index=False)